---
- name: "Infrastructure setup"
  hosts: localhost
  become: yes
  vars:
    # provide application name and service name
    application: [[firewalld,firewalld],[mariadb-server,mariadb],[apache2,apache2],[php,php],[php-mysql,php-mysql]]
  tasks:
    - include_role:
        name: install_applications
      vars:
        application_name: "{{ item[0] }}"
        server_name: "{{ item[1] }}"
      with_items:
        - "{{ application }}"

    