---
- name: "fetch application name"
  debug:
    msg: "{{ application_name }}"

- name: "Install {{ application_name }} - centos"
  yum: name="{{ application_name }}" state=present
  when: ansible_facts['os_family'] == "RedHat"
  ignore_errors: yes

- name: "Install {{ application_name }} - ubuntu"
  apt: name="{{ application_name }}" state=present
  when: ansible_facts['os_family'] == "Debian"
  ignore_errors: yes