---
- name: "Install {{ item }} - centos"
  yum: name="{{ item }}" state=present
  when: ansible_facts['os_family'] == "RedHat"
  with_items: application

- name: "Install {{ item }} - ubuntu"
  apt: name="{{ item }}" state=present
  when: ansible_facts['os_family'] == "Debian"
  with_items: application

- name: "start {{ item }} service"
  service: name="{{ item }}""state=started enabled=true
  with_items: application

#- name: "restart server"
  #reboot:
    #reboot_timeout: 1800

- name: "check the {{ item }} service status"
  ansible.builtin.systemd:
    name: "{{ item }}"
  register: service_state
  debug:
    var: service_state.status.ActiveState
  with_items: application